/*
SQLyog Enterprise - MySQL GUI v8.14 
MySQL - 5.6.16 : Database - workflow
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`workflow` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `workflow`;

/*Table structure for table `wf_header` */

DROP TABLE IF EXISTS `wf_header`;

CREATE TABLE `wf_header` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTRY_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `JOB_CODE` varchar(10) DEFAULT NULL,
  `ACTIVITY_ID` int(11) DEFAULT NULL,
  `PREV_ACTIVITY_ID` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_HEADER_JOB` (`JOB_CODE`),
  KEY `FK_HEADER_ACTIVITY` (`ACTIVITY_ID`),
  KEY `FK_HEADER_PREV_ACTIVITY` (`PREV_ACTIVITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_activity` */

DROP TABLE IF EXISTS `wf_prm_activity`;

CREATE TABLE `wf_prm_activity` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTRY_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PROCESS_ID` int(11) DEFAULT NULL,
  `ORDERS` int(11) DEFAULT NULL,
  `PATH` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `RULES` text,
  PRIMARY KEY (`ID`),
  KEY `FK_ACTIVITY_PROCESS` (`PROCESS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_job` */

DROP TABLE IF EXISTS `wf_prm_job`;

CREATE TABLE `wf_prm_job` (
  `CODE` varchar(10) NOT NULL,
  `ENTRY_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_model` */

DROP TABLE IF EXISTS `wf_prm_model`;

CREATE TABLE `wf_prm_model` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTRY_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PROCESS_ID` int(11) DEFAULT NULL,
  `LABEL` varchar(256) DEFAULT NULL,
  `TYPE_DATA` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_next_flag` */

DROP TABLE IF EXISTS `wf_prm_next_flag`;

CREATE TABLE `wf_prm_next_flag` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTRY_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FROM_ACTIVITY_ID` int(11) DEFAULT NULL,
  `TO_ACTIVITY_ID` int(11) DEFAULT NULL,
  `FLAG` varchar(256) DEFAULT NULL,
  `ORDERS` int(11) DEFAULT NULL,
  `HIDE` tinyint(1) NOT NULL DEFAULT '0',
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `FK_FLAG_TO_ACTIVITY` (`TO_ACTIVITY_ID`),
  KEY `FK_FLAG_FROM_ACTIVITY` (`FROM_ACTIVITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_process` */

DROP TABLE IF EXISTS `wf_prm_process`;

CREATE TABLE `wf_prm_process` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTRY_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `JOB_CODE` varchar(10) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `NOTES` text,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_PROCESS_JOB` (`JOB_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_rules` */

DROP TABLE IF EXISTS `wf_prm_rules`;

CREATE TABLE `wf_prm_rules` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RULE` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Table structure for table `wf_prm_status` */

DROP TABLE IF EXISTS `wf_prm_status`;

CREATE TABLE `wf_prm_status` (
  `ID` int(11) NOT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
